export default {
  extends: ['stylelint-config-standard-scss'],
  customSyntax: 'postcss-scss',
  plugins: ['stylelint-order'],
  rules: {
    'declaration-empty-line-before': null,
    'declaration-property-value-allowed-list': {
      'font-size': [/^fontSize\(\d+px\)$/],
    },
    'declaration-property-value-disallowed-list': {
      'line-height': [/.+/],
    },
    'color-no-hex': true,
    'function-disallowed-list': ['rgb', 'rgba', 'hsl', 'hsla'],
    'function-name-case': null,
    'no-descending-specificity': null,
    'scss/at-function-pattern': '^[a-z][a-zA-Z0-9-]+$',
    'scss/at-mixin-pattern': '^[a-z][a-zA-Z0-9]+$',
    'selector-class-pattern': null,
    'value-keyword-case': null,
    'media-feature-name-disallowed-list': ['width'],
    'order/properties-order': [
      [
        {
          groupName: 'Positioning',
          emptyLineBefore: 'always',
          properties: ['position', 'inset', 'top', 'right', 'bottom', 'left', 'z-index'],
        },
        {
          groupName: 'Display and layout',
          emptyLineBefore: 'always',
          properties: [
            'display',
            'grid-template',
            'grid-template-areas',
            'grid-template-columns',
            'grid-template-rows',
            'grid-column',
            'grid-row',
            'flex',
            'flex-direction',
            'flex-wrap',
            'flex-grow',
            'flex-shrink',
            'flex-basis',
            'align-items',
            'align-self',
            'align-content',
            'justify-content',
            'justify-items',
            'justify-self',
            'place-items',
            'place-content',
            'gap',
            'row-gap',
            'column-gap',
            'float',
            'clear',
          ],
        },
        {
          groupName: 'Box model',
          emptyLineBefore: 'always',
          properties: [
            'box-sizing',
            'width',
            'min-width',
            'max-width',
            'height',
            'min-height',
            'max-height',
            'margin',
            'margin-top',
            'margin-right',
            'margin-bottom',
            'margin-left',
            'padding',
            'padding-top',
            'padding-right',
            'padding-bottom',
            'padding-left',
            'overflow',
            'overflow-x',
            'overflow-y',
            'resize',
          ],
        },
        {
          groupName: 'Border and background',
          emptyLineBefore: 'always',
          properties: [
            'border',
            'border-width',
            'border-style',
            'border-color',
            'border-top',
            'border-right',
            'border-bottom',
            'border-left',
            'border-radius',
            'background',
            'background-color',
            'background-image',
            'background-position',
            'background-size',
            'background-repeat',
          ],
        },
        {
          groupName: 'Typography',
          emptyLineBefore: 'always',
          properties: [
            'color',
            'font',
            'font-family',
            'font-size',
            'font-style',
            'font-weight',
            'letter-spacing',
            'text-align',
            'text-decoration',
            'text-overflow',
            'text-transform',
            'white-space',
            'word-break',
            'overflow-wrap',
          ],
        },
        {
          groupName: 'Visual effects',
          emptyLineBefore: 'always',
          properties: ['opacity', 'visibility', 'box-shadow', 'filter', 'transform', 'transition', 'animation'],
        },
        {
          groupName: 'Interaction',
          emptyLineBefore: 'always',
          properties: ['appearance', 'pointer-events', 'cursor', 'outline', 'user-select'],
        },
      ],
      {
        unspecified: 'bottomAlphabetical',
      },
    ],
  },
  overrides: [
    {
      files: ['src/common/styles/mixins/colors.scss'],
      rules: {
        'color-no-hex': null,
        'function-disallowed-list': null,
      },
    },
    {
      files: ['src/common/styles/mixins/typography.scss'],
      rules: {
        'declaration-property-value-allowed-list': null,
        'declaration-property-value-disallowed-list': {
          'line-height': [/.+/],
        },
      },
    },
  ],
};
